GPU_NUM: 4
CUDA_VISIBLE_DEVICES: 
srun: error: Required nodelist includes more nodes than permitted by max-node count (2 > 1). Eliminating nodes from the nodelist.
CONFIG:
WORLD_SIZE: 4

CONFIG:
WORLD_SIZE: 4

CONFIG:
WORLD_SIZE: 4

CONFIG:
WORLD_SIZE: 4

round 0:
round 0:
round 0:
round 0:
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "all2all_test.py", line 113, in <module>
    main()
  File "all2all_test.py", line 105, in main
    torch.multiprocessing.spawn(comm_test, nprocs=args.gpus, args=(args.gpus, SIZE, 2, 1, args))
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yhy/fold/comm_test/all2all_test.py", line 31, in comm_test
    dist.init_process_group(backend='nccl', init_method=init_method, world_size=world_size, rank=rank, group_name='all2all_test')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).

Traceback (most recent call last):
  File "all2all_test.py", line 113, in <module>
    main()
  File "all2all_test.py", line 105, in main
    torch.multiprocessing.spawn(comm_test, nprocs=args.gpus, args=(args.gpus, SIZE, 2, 1, args))
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yhy/fold/comm_test/all2all_test.py", line 31, in comm_test
    dist.init_process_group(backend='nccl', init_method=init_method, world_size=world_size, rank=rank, group_name='all2all_test')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).

Traceback (most recent call last):
  File "all2all_test.py", line 113, in <module>
    main()
  File "all2all_test.py", line 105, in main
    torch.multiprocessing.spawn(comm_test, nprocs=args.gpus, args=(args.gpus, SIZE, 2, 1, args))
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yhy/fold/comm_test/all2all_test.py", line 31, in comm_test
    dist.init_process_group(backend='nccl', init_method=init_method, world_size=world_size, rank=rank, group_name='all2all_test')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).

srun: error: nico3: tasks 0-2: Exited with exit code 1
GPU_NUM: 4
CUDA_VISIBLE_DEVICES: 
srun: error: Required nodelist includes more nodes than permitted by max-node count (2 > 1). Eliminating nodes from the nodelist.
CONFIG:
WORLD_SIZE: 4

CONFIG:
WORLD_SIZE: 4

CONFIG:
WORLD_SIZE: 4

CONFIG:
WORLD_SIZE: 4

round 0:
round 0:
round 0:
round 0:
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "all2all_test.py", line 113, in <module>
    main()
  File "all2all_test.py", line 105, in main
    torch.multiprocessing.spawn(comm_test, nprocs=args.gpus, args=(args.gpus, SIZE, 2, 1, args))
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yhy/fold/comm_test/all2all_test.py", line 31, in comm_test
    dist.init_process_group(backend='nccl', init_method=init_method, world_size=world_size, rank=rank, group_name='all2all_test')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).

Traceback (most recent call last):
  File "all2all_test.py", line 113, in <module>
    main()
  File "all2all_test.py", line 105, in main
    torch.multiprocessing.spawn(comm_test, nprocs=args.gpus, args=(args.gpus, SIZE, 2, 1, args))
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yhy/fold/comm_test/all2all_test.py", line 31, in comm_test
    dist.init_process_group(backend='nccl', init_method=init_method, world_size=world_size, rank=rank, group_name='all2all_test')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).

Traceback (most recent call last):
  File "all2all_test.py", line 113, in <module>
    main()
  File "all2all_test.py", line 105, in main
    torch.multiprocessing.spawn(comm_test, nprocs=args.gpus, args=(args.gpus, SIZE, 2, 1, args))
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yhy/fold/comm_test/all2all_test.py", line 31, in comm_test
    dist.init_process_group(backend='nccl', init_method=init_method, world_size=world_size, rank=rank, group_name='all2all_test')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).

srun: error: nico3: task 2: Exited with exit code 1
srun: error: nico3: tasks 1,3: Exited with exit code 1
GPU_NUM: 4
CUDA_VISIBLE_DEVICES: 
CONFIG:
WORLD_SIZE: 4

CONFIG:
WORLD_SIZE: 4

CONFIG:
WORLD_SIZE: 4

CONFIG:
WORLD_SIZE: 4

round 0:
round 0:
round 0:
round 0:
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "all2all_test.py", line 113, in <module>
    main()
  File "all2all_test.py", line 105, in main
    torch.multiprocessing.spawn(comm_test, nprocs=args.gpus, args=(args.gpus, SIZE, 2, 1, args))
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yhy/fold/comm_test/all2all_test.py", line 31, in comm_test
    dist.init_process_group(backend='nccl', init_method=init_method, world_size=world_size, rank=rank, group_name='all2all_test')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).

Traceback (most recent call last):
  File "all2all_test.py", line 113, in <module>
    main()
  File "all2all_test.py", line 105, in main
    torch.multiprocessing.spawn(comm_test, nprocs=args.gpus, args=(args.gpus, SIZE, 2, 1, args))
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yhy/fold/comm_test/all2all_test.py", line 31, in comm_test
    dist.init_process_group(backend='nccl', init_method=init_method, world_size=world_size, rank=rank, group_name='all2all_test')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).

Traceback (most recent call last):
  File "all2all_test.py", line 113, in <module>
    main()
  File "all2all_test.py", line 105, in main
    torch.multiprocessing.spawn(comm_test, nprocs=args.gpus, args=(args.gpus, SIZE, 2, 1, args))
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yhy/fold/comm_test/all2all_test.py", line 31, in comm_test
    dist.init_process_group(backend='nccl', init_method=init_method, world_size=world_size, rank=rank, group_name='all2all_test')
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/yhy/.local/anaconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10377 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10377 (errno: 98 - Address already in use).

srun: error: nico3: tasks 1-3: Exited with exit code 1
SIZE: [1, 1024, 1024, 32], in/out_dim: 2/1
SC0: 0.23930668830871582, REAL_BD: 2.6583938190869825 GB/s, TOTAL_BD: 0.9793917656728686 GB/s, comm_vol: 0.234375 GB
SC1: 0.1377098560333252, REAL_BD: 3.722885458435736 GB/s, TOTAL_BD: 1.7019478979288327 GB/s, comm_vol: 0.234375 GB
SC2: 0.11397600173950195, REAL_BD: 3.9509193268072353 GB/s, TOTAL_BD: 2.0563539378726077 GB/s, comm_vol: 0.234375 GB
SC3: 0.12968993186950684, REAL_BD: 3.217191456017401 GB/s, TOTAL_BD: 1.807195027566416 GB/s, comm_vol: 0.234375 GB
A2A: 0.12093281745910645, REAL_BD: 3.6888223172275465 GB/s, TOTAL_BD: 1.9380595352395071 GB/s, comm_vol: 0.234375 GB
AGD: 0.3981637954711914, REAL_BD: 2.6766145985005907 GB/s, TOTAL_BD: 0.5886396570100957 GB/s, comm_vol: 0.234375 GB
SIZE: [1, 1024, 1024, 64], in/out_dim: 2/1
SC0: 0.27935266494750977, REAL_BD: 2.7922182915610563 GB/s, TOTAL_BD: 1.6779864981351722 GB/s, comm_vol: 0.46875 GB
SC1: 0.21694302558898926, REAL_BD: 3.838192177304159 GB/s, TOTAL_BD: 2.160705552655439 GB/s, comm_vol: 0.46875 GB
SC2: 0.2019667625427246, REAL_BD: 4.081588250383801 GB/s, TOTAL_BD: 2.32092644402734 GB/s, comm_vol: 0.46875 GB
SC3: 0.2263500690460205, REAL_BD: 3.289199630972275 GB/s, TOTAL_BD: 2.0709072543057 GB/s, comm_vol: 0.46875 GB
A2A: 0.21338367462158203, REAL_BD: 3.874559396575228 GB/s, TOTAL_BD: 2.1967472480323935 GB/s, comm_vol: 0.46875 GB
AGD: 0.7546210289001465, REAL_BD: 2.751319566249612 GB/s, TOTAL_BD: 0.6211727238547792 GB/s, comm_vol: 0.46875 GB
SIZE: [1, 1024, 1024, 128], in/out_dim: 2/1
SC0: 0.439983606338501, REAL_BD: 2.8955946429734056 GB/s, TOTAL_BD: 2.1307612067680886 GB/s, comm_vol: 0.9375 GB
SC1: 0.33420634269714355, REAL_BD: 3.8975373095965096 GB/s, TOTAL_BD: 2.805153224903211 GB/s, comm_vol: 0.9375 GB
SC2: 0.3229219913482666, REAL_BD: 4.146754450542326 GB/s, TOTAL_BD: 2.903177934973528 GB/s, comm_vol: 0.9375 GB
SC3: 0.37716174125671387, REAL_BD: 3.338486380354778 GB/s, TOTAL_BD: 2.4856709932354826 GB/s, comm_vol: 0.9375 GB
A2A: 0.33307695388793945, REAL_BD: 3.936889680187452 GB/s, TOTAL_BD: 2.814664866652446 GB/s, comm_vol: 0.9375 GB
AGD: 1.4410278797149658, REAL_BD: 2.7936786202537798 GB/s, TOTAL_BD: 0.6505772811178621 GB/s, comm_vol: 0.9375 GB
SIZE: [1, 1024, 1024, 256], in/out_dim: 2/1
SC0: 0.7420768737792969, REAL_BD: 2.997869033461312 GB/s, TOTAL_BD: 2.5266924037814023 GB/s, comm_vol: 1.875 GB
SC1: 0.5953595638275146, REAL_BD: 3.935443959002073 GB/s, TOTAL_BD: 3.1493573193748476 GB/s, comm_vol: 1.875 GB
SC2: 0.5689792633056641, REAL_BD: 4.174438877986338 GB/s, TOTAL_BD: 3.2953749300222253 GB/s, comm_vol: 1.875 GB
SC3: 0.669945478439331, REAL_BD: 3.3585004015035667 GB/s, TOTAL_BD: 2.7987352110620987 GB/s, comm_vol: 1.875 GB
A2A: 0.5891439914703369, REAL_BD: 3.969092760500326 GB/s, TOTAL_BD: 3.1825835910174183 GB/s, comm_vol: 1.875 GB
AGD: 2.833484172821045, REAL_BD: 2.8130877282570994 GB/s, TOTAL_BD: 0.6617294770816494 GB/s, comm_vol: 1.875 GB
SIZE: [1, 1024, 1024, 512], in/out_dim: 2/1
SC0: 1.3776919841766357, REAL_BD: 3.082849130491577 GB/s, TOTAL_BD: 2.721943687754815 GB/s, comm_vol: 3.75 GB
SC1: 1.1028614044189453, REAL_BD: 3.97132094396058 GB/s, TOTAL_BD: 3.4002459284317132 GB/s, comm_vol: 3.75 GB
SC2: 1.0532877445220947, REAL_BD: 4.19896728865192 GB/s, TOTAL_BD: 3.560280673066672 GB/s, comm_vol: 3.75 GB
SC3: 1.2714614868164062, REAL_BD: 3.367983254345552 GB/s, TOTAL_BD: 2.949361847671509 GB/s, comm_vol: 3.75 GB
A2A: 1.102062463760376, REAL_BD: 3.9926890902476253 GB/s, TOTAL_BD: 3.4027109381845086 GB/s, comm_vol: 3.75 GB
AGD: 5.612270355224609, REAL_BD: 2.822446418167837 GB/s, TOTAL_BD: 0.6681787873082463 GB/s, comm_vol: 3.75 GB
SIZE: [1, 1024, 1024, 1024], in/out_dim: 2/1
SC0: 2.6486213207244873, REAL_BD: 3.100507363249405 GB/s, TOTAL_BD: 2.8316618692582662 GB/s, comm_vol: 7.5 GB
SC1: 2.130260705947876, REAL_BD: 3.9896740163826436 GB/s, TOTAL_BD: 3.520695837396492 GB/s, comm_vol: 7.5 GB
SC2: 2.0211970806121826, REAL_BD: 4.204935453120697 GB/s, TOTAL_BD: 3.7106722901699376 GB/s, comm_vol: 7.5 GB
SC3: 2.4630517959594727, REAL_BD: 3.3748734434437657 GB/s, TOTAL_BD: 3.045002956212053 GB/s, comm_vol: 7.5 GB
A2A: 2.108973503112793, REAL_BD: 4.007301104973506 GB/s, TOTAL_BD: 3.556232446225704 GB/s, comm_vol: 7.5 GB
AGD: 14.693154573440552, REAL_BD: 2.742379811226122 GB/s, TOTAL_BD: 0.5104417817503296 GB/s, comm_vol: 7.5 GB
